from siena.shared.exceptions.base import SIENABaseException


class SIENACoreException(SIENABaseException):
    pass
