from siena.shared.exceptions.base import SIENABaseException


class SIENAServerException(SIENABaseException):
    pass
